[tool.poetry]
name = "shib-keygen-api"
version = "0.1.0"
description = "An API which generates Shibboleth SP metadata keys and stores them in Vault"
authors = ["Simon Lundström <simlu+github@su.se>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
