[tool.poetry]
name = "shib-keygen-api"
version = "0.1.0"
description = "An API which generates Shibboleth SP/SAML2 metadata certificate, keys and stores them in e.g. Vault"
authors = ["Simon Lundström <simlu+github@su.se>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3"

[tool.poetry.dev-dependencies]
pytest = "^7"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pylint = "^2.17.5"
black = "^23.7.0"

[tool.pylint]
    [tool.pylint.master]
    disable= [
        'missing-docstring',
        ]

    output-format = 'parseable'

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
